apiVersion: v2
name: play
description: Flink Playground
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: minio
    alias: minio
    version: 5.0.8
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: kafka
    version: 22.0.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kafka.enabled
  - name: kafka-ui
    version: v0.6.2
    repository: https://provectus.github.io/kafka-ui
    condition: kafka-ui.enabled